### ISSUE TITLE
INVALID_ARGUMENT: Cannot convert an array value in an array value

### ISSUE THREAD

**Issue by DKorosec** [jloosli/node-firestore-import-export#20]
### Expected behavior
Exported file should be imported 
### Actual behavior
Got error:
{ Error: 3 INVALID_ARGUMENT: Cannot convert an array value in an array value.
    at new createStatusError ( ... \node_modules\grpc\src\client.js:64:15)
    at  ... \node_modules\grpc\src\client.js:583:15
  code: 3,
  metadata: Metadata { _internal_repr: {} },
  details: 'Cannot convert an array value in an array value.' }

Most of the collections got imported with documents, but others are missing (those with this error).
What is causing this?

**Comment by DKorosec** [comment]
Digging deeper I've found that this happens to documents which have a reference property

**Comment by jloosli** [comment]
@DKorosec Thanks for the details. Do you have a small snippet of data that shows this? From what you've described, does the data look like the following? I'll try to recreate that on my end.

```
{ docA:
  references: [
  collA/docB/collC,
  collA/docD/collE
  ]
}
```

**Comment by DKorosec** [comment]
After some more digging I have found that this issue only happens when deployed to firebase http functions and it affects all reference type fields (doesn't need to be an array).
The following code works perfectly locally, but it's broken when deployed on firebase (refField is not correct)
```
router.get('/dbimportexport', (req, res) => {
    db.collection('test').doc('failedRef').set({
      name: 'ref will fail',
      refField: db.collection('test/some/mock/').doc('refMockDoc')
    }).then(() => {
      firestoreExport(db.collection('test')).then((exported) => {
          res.status(200).send(exported.failedRef.refField);
      });
    });
  });
```

@jloosli do you get the same results?

**Comment by jloosli** [comment]
@DKorosec I don't see this issue when running the import/export from the command line. I haven't tested this library at all within Firebase functions since the data I'm exporting and importing is too large for the plan I'm on (I run into time/lookup limits). I'm hoping I have some time next week to explore and test this more in Firebase functions.

**Comment by DKorosec** [comment]
@jloosli thank you for taking your time, please respond if you will be able to reproduce in firebase functions. The above example code I posted is a minimum example how to reproduce the reference issue in firebase functions (create test collection with one document that has a mocked reference, then export the collection and print the reference field).

**Comment by jloosli** [comment]
@DKorosec I still haven't been able to test this out on my system, but I just pushed out a new version. Could you test it with that and see if it is still causing you problems?

**Comment by DKorosec** [comment]
@jloosli I just tested it, still the same issue with reference type exports :(

**Comment by jloosli** [comment]
@DKorosec I've just published a bunch of bug fixes. I don't know if you're still using this or not, but if you are, I'd love for you to test this and see if it is now working for you.

**Comment by jloosli** [comment]
Latest testing seems like this should be fixed. Closing issue.

**Comment by momoDragon** [comment]
i am still having its issue.

3 INVALID_ARGUMENT: Cannot convert an array value in an array value.
    at Object.exports.createStatusError (/user_code/node_modules/firebase-admin/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:845:24)


this is the data i am adding to a field:
[ [ '-LXRXPFgA6sC9Mg0GQMt', 2, 'Sushi premium' ], [ '-LXRSAp3jpB8EUbZU-0c', 1, 'Caramel Glazed Donuts' ] ]
